# 5.15 List 2 Dimensi

In [2]:
#Pertama membuat variabel untuk list
nomor_punggung = [[1,2,3],
                 [4,5,6],
                 [7,8,9]]
#penggambaran list sama seperti matriks yang dibaca oleh phyton
#baris dimulai dari 0,1,2 dst dan kolom dimulai dari 0,1,2 dst
print("memanggil baris 2,yaitu : ", nomor_punggung[1])
#baris yang muncul adalah baris 2 karena dimulai dari 0
print("memanggil baris 1 kolom 2,yaitu : ", nomor_punggung[0][1])
#list 2 dimensi beralaku Aij

memanggil baris 2,yaitu :  [4, 5, 6]
memanggil baris 1 kolom 2,yaitu :  2


In [4]:
#kita dapat mengubah isi dalam list secara spesifikasi dengan perintah sebagai berikut
nomor_punggung[0][1]=10
#angka yang seharusnya 2 diubah menjadi 10
print(nomor_punggung [0][1])
#dengan kotak pertama sebagai baris dan kotak kedua sebagai kolom

10


In [5]:
#kita dapat memanggil anggota pada list dengan menggunakan for
for angka in nomor_punggung:
    print(angka)
    for nomor_punggung in angka:
        print (nomor_punggung)
#penggunaan for ini memberitahu setiap elemen yang ada pada baris
#sehingga posisi turun dapat dibawa baris 0 kolom 0 adalah satu dan seterusnya sampai baris 2 kolom 2

[1, 10, 3]
1
10
3
[4, 5, 6]
4
5
6
[7, 8, 9]
7
8
9


# 5.16 Tuples

In [7]:
#tuples data yang tidak dapat diubah lagi elemen didalamnnya
#contohnya seperti berikut
angka = (2,4,8,16,32,64)
#elemen yang sudah diisi disini tidak dapat dirubah lagi kedepannya

In [15]:
#memanggil elemen yang ada pada variabel
print("elemen elemen pada variabel angka\n",angka)
#kita juga dapat memanggil elemen yang diinginkan dengan perintah kotak seperti list:
print("memanggil elemen berapapun yang diinginkan\n",angka[2])
#urutan yang dipakai sama seperti sebelumnya yaitu dimulai dari 0
#kita juga dapat memanggil elemen lebih dari 1 dan yang diinginkan
print("elemen urutan 3 hingga seluruhnya \n", angka[2:])


elemen elemen pada variabel angka
 (2, 4, 8, 16, 32, 64)
memanggil elemen berapapun yang diinginkan
 8
elemen urutan 3 hingga seluruhnya 
 (8, 16, 32, 64)


In [27]:
#memanggil elemen pada variabel dan memberitahu elemen yang ada didalam variabel
for bilangan in angka [2:] :
    print ("elemen dari urutan ke 2 pada phyton hingga terakhir "+str(bilangan))


elemen dari urutan ke 2 pada phyton hingga terakhir 8
elemen dari urutan ke 2 pada phyton hingga terakhir 16
elemen dari urutan ke 2 pada phyton hingga terakhir 32
elemen dari urutan ke 2 pada phyton hingga terakhir 64


In [32]:
#berikut adalah contoh tples yang tidak dapat diubah. isi pada variabel tidak dapat diubah
#perintah berikut adalah mencoba untuk mengubah isi variabel tuples
print (angka [0] = 128)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (632526195.py, line 3)

In [29]:
#perintah berikut adalah untuk menambahkan elemen pada variabel tuples
print (angka.append(128))

AttributeError: 'tuple' object has no attribute 'append'

In [30]:
#perintah berikut adalah untuk mengurangi elemen pada variabel tuples
print (angka.remove(5))

AttributeError: 'tuple' object has no attribute 'remove'

Error adalah bukti tuples tidak dapat diubah isi elemen elemennya

In [33]:
#membuat variabel baru
urutan_berulang = (1,2,3,3,2,1,2,3,1)

In [34]:
#kita dapat mengitung ada berapa angka yang sama pada variabel dengan menggunakan
urutan_berulang.count(3)
#output yang muncul adalah banyaknya angka yang sama dalam variabel

3

In [35]:
#peirntah berikut adalah untuk mengetahui elemen ada pada indeks ke berapa
urutan_berulang.index(3)
#pada urutan yang berulang indeks yang dipakai adalah yang pertama kali ditemukan oleh program

2

# 5.17 Dictionaries

In [37]:
#membuat dictionary adalah membuat beberapa data menjadi satu kesatuan atau terkait satu sama lain
#awalnya kita membuat inisialisasi menggunakan kurung kurawal
data_14 = {
    "nama": "Antony",
    "umur":17,
    "mahasiswa ": True
}
#3 data sudah terinput dan saling berkaitan satu dan lainnya
print(data_14)

{'nama': 'Antony', 'umur': 17, 'mahasiswa ': True}


In [41]:
#ini adalah perintah untuk memanggil salah satu data menggunakan kurung siku
print ("nama saya adalah ", data_14['nama'])
#output yang keluar adalah data nama

nama saya adalah  Antony


In [42]:
print("nama saya adalah ", data_14['Nama'])
#output tidak muncul karena ada perbedaan huruf kapital pada nama dan variabel yang dideklarasikan

KeyError: 'Nama'

In [43]:
print(data_14.get('nama'))
#Kita bisa mengatur nilai kunci pada dictionary yang kita panggil

Antony


In [44]:
print(data_orang.get('Nama'))
#output tidak muncul karena ada perbedaan huruf kapital pada "nama"

NameError: name 'data_orang' is not defined

In [45]:
print(data_14.get('tanggal_lahir'))
#perintah ini adalah untuk mencari tau apakah ada data tanggal lahir

None


In [46]:
print(data_14.get('tanggal_lahir', '23-6-2004'))
#perintah ini bertujuan unutk menambahkan tanggal lahir

23-6-2004


In [47]:
print(data_14)
#tetapi pada output yang muncul di print tanggal lahir belum masuk pada data

{'nama': 'Antony', 'umur': 17, 'mahasiswa ': True}


In [48]:
print(data_14["tanggal_lahir"])
#karena tanggal lahir belum masuk pada data mengakibatkan error

KeyError: 'tanggal_lahir'

In [49]:
data_14['no_hp']='08885646'
#perintah sama dengan dan kotak siku dalah perintah untuk menambahkan data kedalam variabel

In [50]:
print(data_14["no_hp"])
#pada output terbukti bahwa data no hp sudah masuk pada variabel data_14

08885646


In [51]:
print(data_14)
#kita dapat melihatnya dengan perintah print ada tambahan nomor hp pada datanya

{'nama': 'Antony', 'umur': 17, 'mahasiswa ': True, 'no_hp': '08885646'}


# 5.18 Fungsi

In [56]:
#fungsi adalah materi lanjutan dari pendahuluan pendahuluan yang sudah dibahas
#pertama menginisialisasi variabel
def full_name(first_name,last_name):
    #ini adalah untuk menginput variabelnya
    print (f"Nama lengkapnya adalah {first_name} {last_name}")

In [57]:
#perintah ini untuk membuat elemen dalam variabel
first_name = input ("Nama depan? ")
last_name = input("Nama belakang? ")
#operasi yang digunakan yaitu menggabungkan nama depan dan nama belakang
full_name(first_name,last_name)

Nama depan? antony
Nama belakang? junior
Nama lengkapnya adalah antony junior


# 5.19.1 Tugas fungsi 

In [58]:
#mendefinisika variabel
def waktu_sampai(jarak,kecepatan):
    #mendefinisikan operasi yang akan dilakukan
    waktu = jarak/kecepatan
    print(waktu)
    #memunculkan output

In [64]:
#data yang diinput adalah 40 sebagai jarak
#dan 15 sebagai kecepatan
waktu_sampai(40,15)
#output yang keluar adalah hasil dari operasi yang sudah didefinisikan sebelumnya


2.6666666666666665


In [67]:
#mendefinisikan variabel yang digunakan
def l_persegi (sisi):
    #operasi yang digunakan
    luas = sisi**2
    #penggunaan return fungsi mengembalikan nilai
    return luas
#menginput nilai yang diinginkan
l_persegi(int(input("Masukkan nilai sisi : ")))
#output yang dikeluarkan adalah hasil dari operasi yang didefinisikan

Masukkan nilai sisi : 3


9

# 5.20 Numpy

In [68]:
#numpy adalah salah satu library phyton
import numpy as np
#jika tidak error maka library yang diimport ada

# 5.20.1 Perintah Dasar pada Numpy 

In [72]:
#membbuat variabel data array dengan ordo yang diinginkan
a = np.array([1,2,3,4])
print (a)
#memggunakan 2 macam kurung siku dan biasa
#output yang muncul adalah matriks ber ordo 1x4

[1 2 3 4]


In [73]:
a.ndim
#adalah penggunaan untuk mengetahhui berapa dimensi pada matriks yang diinput

1

In [74]:
a.shape
#shape untuk mengetahui banyaknya elemen pada matriks

(4,)

In [78]:
#membuat ordo 2x4
b= np.array ([[1,2,3,4],
            [5,6,7,8]])
#setiap baris dipisahkan kurungsiku
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [79]:
b.ndim
#berbeda dengan a. output yang akan dikeluarkan adalah sesuai dengan dimensi yang diinput

2

In [80]:
b.shape
#pada shape variabel b juga akan memiliki output yang berbeda daripada a
#2 untuk baris dan 4 untuk kolom

(2, 4)

In [84]:
c = np.array ([[[3,2,4,1], [2,3,4,5]],
              [[9,8,2,4], [4,5,6,3]],
              [[12,5,7,9], [2,5,4,5]]])
print(c)
#c.ndim untuk menunjukan banyaknya dimensi
c.ndim

[[[ 3  2  4  1]
  [ 2  3  4  5]]

 [[ 9  8  2  4]
  [ 4  5  6  3]]

 [[12  5  7  9]
  [ 2  5  4  5]]]


3

# 5.20.2 Memanggil anggota,kolom,dan baris

In [85]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [86]:
#perintah untuk memanggil pada elemen baris ke 1 dan kolom ke 3
print (b[0,2])

3


In [88]:
#memanggil seluruh elemen yang ada pada variabel 
print (b[ : ])

[[1 2 3 4]
 [5 6 7 8]]


In [90]:
#memanggil elemen dari baris yang diinginkan sampai baris terakhir
print (b[1: ])

[[5 6 7 8]]


In [91]:
#memanggil elemen dari kolom yang diinginkan
print (b[:,2])

[3 7]


In [94]:
#memanggil elemen dari baris dan kolom yang diinginkan hingga kolom yang dituju
print (b[0,1:3])

[2 3]


In [97]:
#memanggil elemen dari baris dan kolom yang diinginkan dan kolom yang dituju
print (b[0,0:2:1]) 

[1 2]


In [98]:
#mengubah satu elemen yang ada didalam variabel
b[0,0]=100
print (b)

[[100   2   3   4]
 [  5   6   7   8]]


# 5.20.3 Matriks pada numpy

In [99]:
#Numpy dapat digunakan untuk memunculkan berbagai macam matriks
#kita dapat memanggilnya dengan perintah
np.ones((2,3))
#ones artinya matriks angka matrik 2 sebagai baris dan 3 sebagai kolom

array([[1., 1., 1.],
       [1., 1., 1.]])

In [100]:
#perintah berikutnya memanggil jenis matriks lain
np.zeros((3,3))
#seperti sebelumnya (3,3) berarti berordo 3x3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [102]:
#memanggil matriks indentitas
np.identity(4)
#4 berarti ordo 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
#memanggil 2 buah matriks dengan ordo 3x4
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [104]:
#memanggil matriks dengan ordo 3x2 dengan semuanya berisi angka yang diinginkan
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [105]:
#memanggil matriks dengan nilai random dengan baris 4 dan kolom 3
np.random.rand(4,3)

array([[0.14178217, 0.41456143, 0.04174481],
       [0.72443275, 0.51731016, 0.42787997],
       [0.52257876, 0.62633641, 0.170009  ],
       [0.16206559, 0.36539867, 0.79513693]])

In [106]:
#membuat matrik random dengan batasan yang ditentukan dan ordo yang diinginkan
np.random.randint(2,7, size=(3,3))

array([[4, 5, 3],
       [5, 5, 6],
       [4, 5, 4]])

# 5.20.4 Copy pada Numpy

In [107]:
print(a)

[1 2 3 4]


In [108]:
#jika memasukan variabel baru dengan menggunakan variabel yang lama maka nilainya sama
k = a

In [109]:
print(k)
#outputnya adalah nilai a pada awal

[1 2 3 4]


In [113]:
#mengubah elemen yang dinginkan dengan nilai yang dinginkan
k [0] = 10
print(k)

[10  2  3  4]


In [114]:
print(a)
#karena nilai k sama dengan a maka nilai yang diubah pada k berpengaruh pada a

[10  2  3  4]


In [115]:
#membuat variabel baru
e = np.array ([3,4,5,6,7])
print(e)

[3 4 5 6 7]


In [116]:
#perintah yang berbeda tapi menghasilkan output sama
#copy berguna seperti sama dengan
j = e.copy()
print(j)

[3 4 5 6 7]


In [117]:
j[2]=9
print(j)
#mengubah satu elemen

[3 4 9 6 7]


In [118]:
print (e)
#tapi tidak berpengaruh pada e yang sudah dikopi oleh j tadi

[3 4 5 6 7]


# 5.20.5 Operasi Matematika Pada Numpy

In [119]:
print(e)

[3 4 5 6 7]


In [121]:
#operasi penjumlahan menjumlahkan seluruh isi matriks dengan nilai yang diinput
e+int(input("Masukkan nilai : "))

Masukkan nilai : 2


array([5, 6, 7, 8, 9])

In [122]:
#berlaku pada pengurangan
e-int(input("Masukkan nilai : "))

Masukkan nilai : 2


array([1, 2, 3, 4, 5])

In [126]:
#berlaku pada perkalian, pembagian dan pangkat
e*int(input("Masukkan nilai : "))

Masukkan nilai : 2


array([ 6,  8, 10, 12, 14])

In [125]:
e/int(input("Masukkan nilai : "))

Masukkan nilai : 2


array([1.5, 2. , 2.5, 3. , 3.5])

In [127]:
e**int(input("Masukkan nilai : "))

Masukkan nilai : 2


array([ 9, 16, 25, 36, 49], dtype=int32)

In [128]:
print(a)

[10  2  3  4]


In [129]:
#menggunakan operasi yang sama untuk mengoperasikan dua buah matriks

In [131]:
a+e

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [132]:
#error karena tidak sesuai dengan ordo yang diperlukan

In [133]:
print(j)

[3 4 9 6 7]


In [134]:
e+j
#berlaku karena ordo sesuai

array([ 6,  8, 14, 12, 14])

In [135]:
e-j

array([ 0,  0, -4,  0,  0])

In [136]:
e*j

array([ 9, 16, 45, 36, 49])

In [137]:
e**j

array([     27,     256, 1953125,   46656,  823543], dtype=int32)

In [138]:
np.cos(e)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.75390225])

In [140]:
np.tan(e)

array([-0.14254654,  1.15782128, -3.38051501, -0.29100619,  0.87144798])

In [141]:
np.sinh(e)

array([ 10.01787493,  27.2899172 ,  74.20321058, 201.71315737,
       548.31612327])

# 5.20.6 perkalian matrik pada numpy

In [142]:
print (b)

[[10 10 10 10]
 [ 5  6  7  8]]


In [151]:
l = np.random.randint(2,7, size=(2,4))
print(l)

[[3 2 3 6]
 [6 6 3 4]]


In [152]:
g = b*l
print(g)

[[30 20 30 60]
 [30 36 21 32]]


In [153]:
n = np.random.randint(2,7, size=(4,3))
print(n)

[[6 4 5]
 [5 3 4]
 [6 2 2]
 [3 5 6]]


In [154]:
h = g*n

ValueError: operands could not be broadcast together with shapes (2,4) (4,3) 

In [155]:
#error karena ordo dalam perkalian tidak sesuai

# 5.20.7 min,max, dan sum pada numpy

In [160]:
#memanggil matrik
x = np.random.randint(2,9, size=(3,4))
print(x)

[[2 3 4 6]
 [8 7 6 5]
 [6 7 5 8]]


In [161]:
b = np.min(x)
print(b)

2


In [162]:
c = np.min(a,axis=0)
print(c)

[3 2 3]


In [163]:
d = np.min(a,axis=1)
print(d)

[5 3 3 2]


In [164]:
e= np.max(a)
print(e)

6


In [165]:
f = np.max(a,axis=0)
print(f)

[5 6 5]


In [166]:
h = np.sum(a)
print(h)

51


In [167]:
h = np.sum(a,axis=0)
print(h)

[18 17 16]
